Build fix: set EXA_DRIVER_KNOWN_MAJOR=3.
We don't use {Prepare,Finish}Access, and:

/home/cjb/xorg-build/include/xorg/exa.h:45:2: error: #error Make sure
this EXA driver either does not have Prepare/FinishAccess hooks or that
they can handle EXA_PREPARE_AUX*, and #define EXA_DRIVER_KNOWN_MAJOR 3
before including exa.h

Signed-off-by: Chris Ball <cjb@laptop.org>